version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_APP=app/__init__.py
    env_file:
      - .env
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000 --reload
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"