# version: '3.8'

services:
  jupyter:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - .:/app
    command: jupyter notebook --ip=0.0.0.0 --port=5000 --no-browser --allow-root
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"