"""Add academic_year to UCAdmissionEthnicity

Revision ID: 3e0e479e3342
Revises: 
Create Date: 2024-09-02 03:27:33.383394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0e479e3342'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uc_admission_ethnicity', sa.Column('academic_year', sa.Integer(), nullable=True))
    op.add_column('uc_admission_gender', sa.Column('academic_year', sa.Integer(), nullable=True))
    op.drop_column('uc_admission_gender', 'year')
    op.add_column('uc_admission_gpa', sa.Column('academic_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uc_admission_gpa', 'academic_year')
    op.add_column('uc_admission_gender', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('uc_admission_gender', 'academic_year')
    op.drop_column('uc_admission_ethnicity', 'academic_year')
    # ### end Alembic commands ###
