"""Add new uc school name to high school table

Revision ID: c47c773b1190
Revises: 3e0e479e3342
Create Date: 2024-09-02 06:17:29.648202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47c773b1190'
down_revision: Union[str, None] = '3e0e479e3342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('high_schools', sa.Column('uc_school_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_high_schools_city'), 'high_schools', ['city'], unique=False)
    op.create_index(op.f('ix_high_schools_uc_school_name'), 'high_schools', ['uc_school_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_high_schools_uc_school_name'), table_name='high_schools')
    op.drop_index(op.f('ix_high_schools_city'), table_name='high_schools')
    op.drop_column('high_schools', 'uc_school_name')
    # ### end Alembic commands ###
